# Generated by Django 2.0.3 on 2018-03-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Comment',
        ),
    ]
